// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: cs-mw.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define an enum
type PingType int32

const (
	PingType_ACTIVATE   PingType = 0 // Default value
	PingType_PING       PingType = 1
	PingType_DEACTIVATE PingType = 2
)

// Enum value maps for PingType.
var (
	PingType_name = map[int32]string{
		0: "ACTIVATE",
		1: "PING",
		2: "DEACTIVATE",
	}
	PingType_value = map[string]int32{
		"ACTIVATE":   0,
		"PING":       1,
		"DEACTIVATE": 2,
	}
)

func (x PingType) Enum() *PingType {
	p := new(PingType)
	*p = x
	return p
}

func (x PingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PingType) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_mw_proto_enumTypes[0].Descriptor()
}

func (PingType) Type() protoreflect.EnumType {
	return &file_cs_mw_proto_enumTypes[0]
}

func (x PingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PingType.Descriptor instead.
func (PingType) EnumDescriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{0}
}

type CancelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	InnerID int32 `protobuf:"varint,2,opt,name=InnerID,proto3" json:"InnerID,omitempty"`
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_mw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cs_mw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{0}
}

func (x *CancelRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *CancelRequest) GetInnerID() int32 {
	if x != nil {
		return x.InnerID
	}
	return 0
}

type CancelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *CancelReply) Reset() {
	*x = CancelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_mw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReply) ProtoMessage() {}

func (x *CancelReply) ProtoReflect() protoreflect.Message {
	mi := &file_cs_mw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReply.ProtoReflect.Descriptor instead.
func (*CancelReply) Descriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{1}
}

func (x *CancelReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Matrix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*Row `protobuf:"bytes,1,rep,name=Rows,proto3" json:"Rows,omitempty"`
}

func (x *Matrix) Reset() {
	*x = Matrix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_mw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Matrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix) ProtoMessage() {}

func (x *Matrix) ProtoReflect() protoreflect.Message {
	mi := &file_cs_mw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix.ProtoReflect.Descriptor instead.
func (*Matrix) Descriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{2}
}

func (x *Matrix) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []float32 `protobuf:"fixed32,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_mw_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_cs_mw_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConvolutionalLayerFrontRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target      *Matrix   `protobuf:"bytes,1,opt,name=Target,proto3" json:"Target,omitempty"`
	Kernel      []*Matrix `protobuf:"bytes,2,rep,name=Kernel,proto3" json:"Kernel,omitempty"`
	AvgPoolSize int32     `protobuf:"varint,3,opt,name=AvgPoolSize,proto3" json:"AvgPoolSize,omitempty"`
	UseKernels  bool      `protobuf:"varint,4,opt,name=UseKernels,proto3" json:"UseKernels,omitempty"`
	UseSigmoid  bool      `protobuf:"varint,5,opt,name=UseSigmoid,proto3" json:"UseSigmoid,omitempty"`
}

func (x *ConvolutionalLayerFrontRequest) Reset() {
	*x = ConvolutionalLayerFrontRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_mw_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvolutionalLayerFrontRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvolutionalLayerFrontRequest) ProtoMessage() {}

func (x *ConvolutionalLayerFrontRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cs_mw_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvolutionalLayerFrontRequest.ProtoReflect.Descriptor instead.
func (*ConvolutionalLayerFrontRequest) Descriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{4}
}

func (x *ConvolutionalLayerFrontRequest) GetTarget() *Matrix {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ConvolutionalLayerFrontRequest) GetKernel() []*Matrix {
	if x != nil {
		return x.Kernel
	}
	return nil
}

func (x *ConvolutionalLayerFrontRequest) GetAvgPoolSize() int32 {
	if x != nil {
		return x.AvgPoolSize
	}
	return 0
}

func (x *ConvolutionalLayerFrontRequest) GetUseKernels() bool {
	if x != nil {
		return x.UseKernels
	}
	return false
}

func (x *ConvolutionalLayerFrontRequest) GetUseSigmoid() bool {
	if x != nil {
		return x.UseSigmoid
	}
	return false
}

type ConvolutionalLayerFrontReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*Matrix `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
	ID     int32     `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ConvolutionalLayerFrontReply) Reset() {
	*x = ConvolutionalLayerFrontReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_mw_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvolutionalLayerFrontReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvolutionalLayerFrontReply) ProtoMessage() {}

func (x *ConvolutionalLayerFrontReply) ProtoReflect() protoreflect.Message {
	mi := &file_cs_mw_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvolutionalLayerFrontReply.ProtoReflect.Descriptor instead.
func (*ConvolutionalLayerFrontReply) Descriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{5}
}

func (x *ConvolutionalLayerFrontReply) GetResult() []*Matrix {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ConvolutionalLayerFrontReply) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ConvolutionalLayerBackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target      *Matrix   `protobuf:"bytes,1,opt,name=Target,proto3" json:"Target,omitempty"`
	Kernel      []*Matrix `protobuf:"bytes,2,rep,name=Kernel,proto3" json:"Kernel,omitempty"`
	AvgPoolSize int32     `protobuf:"varint,3,opt,name=AvgPoolSize,proto3" json:"AvgPoolSize,omitempty"`
	UseKernels  bool      `protobuf:"varint,5,opt,name=UseKernels,proto3" json:"UseKernels,omitempty"`
	UseSigmoid  bool      `protobuf:"varint,6,opt,name=UseSigmoid,proto3" json:"UseSigmoid,omitempty"`
	ID          int32     `protobuf:"varint,7,opt,name=ID,proto3" json:"ID,omitempty"`
	InnerID     int32     `protobuf:"varint,8,opt,name=InnerID,proto3" json:"InnerID,omitempty"`
}

func (x *ConvolutionalLayerBackRequest) Reset() {
	*x = ConvolutionalLayerBackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_mw_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvolutionalLayerBackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvolutionalLayerBackRequest) ProtoMessage() {}

func (x *ConvolutionalLayerBackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cs_mw_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvolutionalLayerBackRequest.ProtoReflect.Descriptor instead.
func (*ConvolutionalLayerBackRequest) Descriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{6}
}

func (x *ConvolutionalLayerBackRequest) GetTarget() *Matrix {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ConvolutionalLayerBackRequest) GetKernel() []*Matrix {
	if x != nil {
		return x.Kernel
	}
	return nil
}

func (x *ConvolutionalLayerBackRequest) GetAvgPoolSize() int32 {
	if x != nil {
		return x.AvgPoolSize
	}
	return 0
}

func (x *ConvolutionalLayerBackRequest) GetUseKernels() bool {
	if x != nil {
		return x.UseKernels
	}
	return false
}

func (x *ConvolutionalLayerBackRequest) GetUseSigmoid() bool {
	if x != nil {
		return x.UseSigmoid
	}
	return false
}

func (x *ConvolutionalLayerBackRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ConvolutionalLayerBackRequest) GetInnerID() int32 {
	if x != nil {
		return x.InnerID
	}
	return 0
}

type ConvolutionalLayerBackReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  []*Matrix `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
	ID      int32     `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	InnerID int32     `protobuf:"varint,3,opt,name=InnerID,proto3" json:"InnerID,omitempty"`
}

func (x *ConvolutionalLayerBackReply) Reset() {
	*x = ConvolutionalLayerBackReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_mw_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvolutionalLayerBackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvolutionalLayerBackReply) ProtoMessage() {}

func (x *ConvolutionalLayerBackReply) ProtoReflect() protoreflect.Message {
	mi := &file_cs_mw_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvolutionalLayerBackReply.ProtoReflect.Descriptor instead.
func (*ConvolutionalLayerBackReply) Descriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{7}
}

func (x *ConvolutionalLayerBackReply) GetResult() []*Matrix {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ConvolutionalLayerBackReply) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ConvolutionalLayerBackReply) GetInnerID() int32 {
	if x != nil {
		return x.InnerID
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerAddress string   `protobuf:"bytes,1,opt,name=WorkerAddress,proto3" json:"WorkerAddress,omitempty"`
	QueueSize     int32    `protobuf:"varint,2,opt,name=QueueSize,proto3" json:"QueueSize,omitempty"`
	UsageCPU      float32  `protobuf:"fixed32,3,opt,name=UsageCPU,proto3" json:"UsageCPU,omitempty"`
	Type          PingType `protobuf:"varint,4,opt,name=Type,proto3,enum=mini.PingType" json:"Type,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_mw_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cs_mw_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{8}
}

func (x *PingRequest) GetWorkerAddress() string {
	if x != nil {
		return x.WorkerAddress
	}
	return ""
}

func (x *PingRequest) GetQueueSize() int32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *PingRequest) GetUsageCPU() float32 {
	if x != nil {
		return x.UsageCPU
	}
	return 0
}

func (x *PingRequest) GetType() PingType {
	if x != nil {
		return x.Type
	}
	return PingType_ACTIVATE
}

type PingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_mw_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_cs_mw_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_cs_mw_proto_rawDescGZIP(), []int{9}
}

func (x *PingReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_cs_mw_proto protoreflect.FileDescriptor

var file_cs_mw_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x73, 0x2d, 0x6d, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x69, 0x6e, 0x69, 0x22, 0x39, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x25,
	0x0a, 0x0b, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x27, 0x0a, 0x06, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x12,
	0x1d, 0x0a, 0x04, 0x52, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x1d,
	0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xce, 0x01,
	0x0a, 0x1e, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x4c,
	0x61, 0x79, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x24, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x06,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x4d, 0x61,
	0x74, 0x72, 0x69, 0x78, 0x52, 0x06, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b,
	0x41, 0x76, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x41, 0x76, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x55, 0x73, 0x65, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x55, 0x73, 0x65, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x55, 0x73, 0x65, 0x53, 0x69, 0x67, 0x6d, 0x6f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x55, 0x73, 0x65, 0x53, 0x69, 0x67, 0x6d, 0x6f, 0x69, 0x64, 0x22, 0x54,
	0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x4c,
	0x61, 0x79, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x44, 0x22, 0xf7, 0x01, 0x0a, 0x1d, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x4d, 0x61,
	0x74, 0x72, 0x69, 0x78, 0x52, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x06,
	0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d,
	0x69, 0x6e, 0x69, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x06, 0x4b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x76, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x41, 0x76, 0x67, 0x50, 0x6f, 0x6f, 0x6c,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x4b, 0x65, 0x72, 0x6e, 0x65,
	0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x55, 0x73, 0x65, 0x4b, 0x65, 0x72,
	0x6e, 0x65, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x53, 0x69, 0x67, 0x6d, 0x6f,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x55, 0x73, 0x65, 0x53, 0x69, 0x67,
	0x6d, 0x6f, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x6d,
	0x0a, 0x1b, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x4c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x91, 0x01,
	0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x61, 0x67, 0x65, 0x43, 0x50, 0x55, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x08, 0x55, 0x73, 0x61, 0x67, 0x65, 0x43, 0x50, 0x55, 0x12, 0x22, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x69,
	0x6e, 0x69, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x23, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x32, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x43, 0x54, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45,
	0x41, 0x43, 0x54, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x02, 0x32, 0x69, 0x0a, 0x05, 0x46, 0x72,
	0x6f, 0x6e, 0x74, 0x12, 0x60, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x6d, 0x69, 0x6e, 0x69,
	0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x4c, 0x61,
	0x79, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x32, 0x9a, 0x01, 0x0a, 0x04, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x32,
	0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x13, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x5e, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x2e,
	0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x4c, 0x61, 0x79,
	0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x32, 0x3c, 0x0a, 0x06, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x0a,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x6d, 0x69, 0x6e,
	0x69, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x6d, 0x69, 0x6e, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_mw_proto_rawDescOnce sync.Once
	file_cs_mw_proto_rawDescData = file_cs_mw_proto_rawDesc
)

func file_cs_mw_proto_rawDescGZIP() []byte {
	file_cs_mw_proto_rawDescOnce.Do(func() {
		file_cs_mw_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_mw_proto_rawDescData)
	})
	return file_cs_mw_proto_rawDescData
}

var file_cs_mw_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cs_mw_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cs_mw_proto_goTypes = []interface{}{
	(PingType)(0),                          // 0: mini.PingType
	(*CancelRequest)(nil),                  // 1: mini.CancelRequest
	(*CancelReply)(nil),                    // 2: mini.CancelReply
	(*Matrix)(nil),                         // 3: mini.Matrix
	(*Row)(nil),                            // 4: mini.Row
	(*ConvolutionalLayerFrontRequest)(nil), // 5: mini.ConvolutionalLayerFrontRequest
	(*ConvolutionalLayerFrontReply)(nil),   // 6: mini.ConvolutionalLayerFrontReply
	(*ConvolutionalLayerBackRequest)(nil),  // 7: mini.ConvolutionalLayerBackRequest
	(*ConvolutionalLayerBackReply)(nil),    // 8: mini.ConvolutionalLayerBackReply
	(*PingRequest)(nil),                    // 9: mini.PingRequest
	(*PingReply)(nil),                      // 10: mini.PingReply
}
var file_cs_mw_proto_depIdxs = []int32{
	4,  // 0: mini.Matrix.Rows:type_name -> mini.Row
	3,  // 1: mini.ConvolutionalLayerFrontRequest.Target:type_name -> mini.Matrix
	3,  // 2: mini.ConvolutionalLayerFrontRequest.Kernel:type_name -> mini.Matrix
	3,  // 3: mini.ConvolutionalLayerFrontReply.Result:type_name -> mini.Matrix
	3,  // 4: mini.ConvolutionalLayerBackRequest.Target:type_name -> mini.Matrix
	3,  // 5: mini.ConvolutionalLayerBackRequest.Kernel:type_name -> mini.Matrix
	3,  // 6: mini.ConvolutionalLayerBackReply.Result:type_name -> mini.Matrix
	0,  // 7: mini.PingRequest.Type:type_name -> mini.PingType
	5,  // 8: mini.Front.ConvolutionalLayer:input_type -> mini.ConvolutionalLayerFrontRequest
	1,  // 9: mini.Back.Cancel:input_type -> mini.CancelRequest
	7,  // 10: mini.Back.ConvolutionalLayer:input_type -> mini.ConvolutionalLayerBackRequest
	9,  // 11: mini.Master.NotifyPing:input_type -> mini.PingRequest
	6,  // 12: mini.Front.ConvolutionalLayer:output_type -> mini.ConvolutionalLayerFrontReply
	2,  // 13: mini.Back.Cancel:output_type -> mini.CancelReply
	8,  // 14: mini.Back.ConvolutionalLayer:output_type -> mini.ConvolutionalLayerBackReply
	10, // 15: mini.Master.NotifyPing:output_type -> mini.PingReply
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cs_mw_proto_init() }
func file_cs_mw_proto_init() {
	if File_cs_mw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cs_mw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_mw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_mw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Matrix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_mw_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_mw_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvolutionalLayerFrontRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_mw_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvolutionalLayerFrontReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_mw_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvolutionalLayerBackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_mw_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvolutionalLayerBackReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_mw_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_mw_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_mw_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_cs_mw_proto_goTypes,
		DependencyIndexes: file_cs_mw_proto_depIdxs,
		EnumInfos:         file_cs_mw_proto_enumTypes,
		MessageInfos:      file_cs_mw_proto_msgTypes,
	}.Build()
	File_cs_mw_proto = out.File
	file_cs_mw_proto_rawDesc = nil
	file_cs_mw_proto_goTypes = nil
	file_cs_mw_proto_depIdxs = nil
}
